config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  devise_for :users

  namespace :api do
    resources :users
    resources :tickets
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text(65535)
#  status      :integer          default("new")
#  reporter_id :integer
#  assignee_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ticket < ApplicationRecord
  include AASM

  belongs_to :reporter, class_name: User.name
  belongs_to :assignee, class_name: User.name, required: false

  validates :title, presence: true, length: { in: 10..255 }
  validates :description, presence: true, length: { maximum: 5000 }

  enum status: {
    submitted: 0,
    assigned: 1,
    in_progress: 1,
    resolved: 2,
    closed: 3,
    reopened: 4
  }

  aasm column: :status, enum: true do
    state :submitted, initial: true
    state :assigned
    state :resolved
    state :closed
    state :reopened

    event :assign do
      transitions from: :submitted, to: :assigned
    end

    event :start do
      transitions from: [:assigned, :reopened], to: :in_progress
    end

    event :resolve do
      transitions from: :in_progress, to: :resolved
    end

    event :close do
      transitions from: :resolved, to: :closed
    end

    event :reopen do
      transitions from: :resolved, to: :reopened
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string(255)
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/api.rb
module Api
end

app/controllers/api/tickets_controller.rb
class Api::TicketsController < ApiController
  include ResourceApi

  respond_to :json

  private

  def resource_class
    Ticket
  end

  def resource_params
    params.require(:ticket).permit(:title, :description)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  include ResourceApi

  respond_to :json

  private

  def resource_class
    User
  end

  def resource_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/resource_api.rb
module ResourceApi
  def index
    respond_with(resource_class.all)
  end

  def create
    @record = resource_class.create(resource_params)
    resource_response(@record, :created)
  end

  def update
    @record = resource
    @record.update_attributes(resource_params)
    resource_response(@record)
  end

  def destroy
    resource.destroy
    head :no_content
  end

  private

  def resource_class
    raise NotImplementedError
  end

  def resource_params
    raise NotImplementedError
  end

  def resource
    resource_class.find(params[:id])
  end

  def resource_response(record, status = :ok)
    if record.valid?
      render json: record, status: status
    else
      render json: record.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    flash.map do |type, text|
      { id: text.object_id, type: type, text: text }
    end
  end
end

app/views/dashboard/index.html.slim
//= react_component('AdminDashboard', users_url: admin_users_path)

#root

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Rails Tickets
    = csrf_meta_tags
    = stylesheet_pack_tag 'admin'
    = javascript_pack_tag 'admin'
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" \
                                         aria-expanded="false" \
                                         data-target="#navbar" \
                                         data-toggle="collapse" \
                                         type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Rails Tickets', root_path, class: 'navbar-brand'
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav.pull-right
            - if user_signed_in?
              li
                p.navbar-text
                  span class="glyphicon glyphicon-user" aria-hidden="true"
                  | &nbsp;
                  = current_user.email
              li= link_to t('.sign_out', default: 'Sign Out'), destroy_session_path(:user), method: :delete
    .container.page-content
      = react_component('Shared.AlertsList', messages: flash_messages)
      = yield